services:
  - type: web
    name: divtrack
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: divtrack-db
          property: connectionString
  - type: pserv
    name: divtrack-db
    plan: free
    databaseName: divtrack
    user: divtrack
